version: '3'

services:

  db:
    image: mysql:5
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: struts
      MYSQL_DATABASE: struts
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - my-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8181:80
    depends_on:
      - db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: struts
      PMA_HOST: db

volumes:
  my-data: