package com.example.demo.controller;

import com.example.demo.entity.User;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * The type Welcome controller.
 */
@Controller
public class WelcomeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    /**
     * Main string.
     *
     * @param model the model
     * @return the string
     */
    @GetMapping("/")
    public String main(Model model) {
        model.addAttribute("message", "toto!");

        return "index";
    }

    /**
     * Add new user string.
     *
     * @return the string
     */
    @GetMapping(path="/adduser") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser () {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName("toto");
        n.setEmail("toto@uqac.ca");
        userRepository.save(n);
        return "Saved";
    }

    /**
     * Hello string.
     *
     * @return the string
     */
    @GetMapping("/hello")
    public String hello() {
        return "hello";
    }

}
